Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 60 
Documentation:
  Exclude:
    - db/**/*
    - app/helpers/**/*
Metrics/AbcSize:
  Enabled: false
Style/PredicateName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
