version: '2'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ya
    ports:
      - 3000:3000
    expose:
      - '3000'
#    mem_limit: 250m
    networks:
      - back-tier
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/ya
      - /data/docker/nginx/ssl:/etc/nginx/conf.d/ssl
    mem_limit: 50m
    networks:
      - back-tier
  db:
    restart: always
    image: mdillon/postgis:9.5
    mem_limit: 50m
    networks:
      - back-tier
    #environment:
    #  MYSQL_ROOT_PASSWORD:
    #  MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #  MYSQL_DATABASE: young_aggrarians_production

networks:
  back-tier:
    driver: bridge

volumes:
  db:
    driver: local
