youngAggrariansApp:
  restart: always
  build:
    dockerfile: Dockerfile
  command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
  ports:
    - 127.0.0.1:3000:3000
  environment:
    RAILS_ENV: production
  volumes:
    - log:/ya/log
    - secrets:/ya/config/secrets
  expose:
    - '3000'
  mem_limit: 250m
  links:
    - youngAggrariansDb:mysql
youngAggrariansFrontend:
  restart: always
  build:
    dockerfile: Dockerfile.frontend
  ports:
    - 80:80
    - 443:443
  links:
    - youngAggrariansApp:app
  volumes:
    - /data/docker/nginx/ssl:/etc/nginx/conf.d/ssl
  mem_limit: 50m
youngAggrariansDb:
  restart: always
  image: "mysql:5.6"
  mem_limit: 50m
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_DATABASE: young_aggrarians_production
