version: '2'
<<<<<<< HEAD

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 127.0.0.1:3000:3000
    #environment:
    #  RAILS_ENV: production
    volumes:
      #- ./log:/ya/log
      #- ./secrets:/ya/config/secrets
      - .:/ya
    expose:
      - '3000'
    mem_limit: 250m
    networks:
      - back-tier
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend

    volumes:
      - /data/docker/nginx/ssl:/etc/nginx/conf.d/ssl
    mem_limit: 50m
    networks:
      - back-tier
  db:
    restart: always
    image: "postgres:9.5"
    mem_limit: 50m
    networks:
      - back-tier
    #environment:
    #  MYSQL_ROOT_PASSWORD:
    #  MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #  MYSQL_DATABASE: young_aggrarians_production

networks:
  back-tier:
    driver: bridge

volumes:
  db:
    driver: local
=======
services:
  young_aggrarians_app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 80:3000
    environment:
      RAILS_ENV: production
    volumes:
      - /data/ya-secrets:/ya/config/secrets:ro
    expose:
      - '3000'
    # mem_limit: 350m
    links:
      - young_aggrarians_db:pg
  # youngAggrariansFrontend:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - youngAggrariansApp:app
  #   volumes:
  #     - /data/docker/nginx/ssl:/etc/nginx/conf.d/ssl
  #   mem_limit: 50m
  young_aggrarians_db:
    restart: always
    image: postgres:9.5
    mem_limit: 50m
    volumes:
      - /data/:/dumps:ro
    environment:
      POSTGRES_PASSWORD: sekrit
>>>>>>> 55274b3d1622d66bf386900abe414fd353c8e220
