
services:
  young_aggrarians_app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 80:3000
    environment:
      RAILS_ENV: production
    volumes:
      - /data/ya-secrets:/ya/config/secrets:ro
    expose:
      - '3000'
    # mem_limit: 350m
    links:
      - young_aggrarians_db:pg
  # youngAggrariansFrontend:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - youngAggrariansApp:app
  #   volumes:
  #     - /data/docker/nginx/ssl:/etc/nginx/conf.d/ssl
  #   mem_limit: 50m
  young_aggrarians_db:
    restart: always
    image: postgres:9.5
    mem_limit: 50m
    volumes:
      - /data/:/dumps:ro
    environment:
      POSTGRES_PASSWORD: sekrit

