Rails.application.config.assets.precompile += %w( marketing.css basic.css new_listing.css locations_crud.css messages.css)
Rails.application.config.assets.precompile += %w( embedded_map.js )
Rails.application.config.assets.precompile += %w( forms.js )
Rails.application.config.assets.precompile += %w( global.js )
Rails.application.config.assets.precompile += %w( js-webshim/minified/polyfiller.js )
