send_mail_to: 'admin@youngagrarians.org'
send_from: '"Young Agrarians" <no-reply@youngagrarians.org>'
smtp_host: 'smtp.sengrid.net'
smtp_port: 587
smtp_username: ''
smtp_password: ''

development:
  mailer_host: '192.168.1.15:3000'
  send_mail_to: 'echo85@gmail.com'

test:
  mailer_host: '192.168.1.15:3000'

staging:
  mailer_host: 'staging.map.youngagrarians.org'

production:
  mailer_host: 'map.youngagrarians.org'
  smtp_host: 'smtp.sendgrid.net'
  smtp_username: <%= ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SENDGRID_PASSWORD"] %>
