development:
  database: postgres
  adapter: postgresql
  reconnect: true
  pool: 5
  username: postgres
  password: postgres
  host: db

production:
  database: postgres
  adapter: postgresql
  reconnect: true
  pool: 5
  username: postgres
  password: postgres
  host: db
